### ISSUE TITLE
Next slide title needed

### ISSUE THREAD

**Issue by ghost** [washingtonstateuniversity/nursing.wsu.edu#9]
On [line 49](https://github.com/washingtonstateuniversity/nursing.wsu.edu/blob/feature-next-slideshow/builder-templates/front-end/banner.php#L49) on [front-end/banner.php](https://github.com/washingtonstateuniversity/nursing.wsu.edu/blob/feature-next-slideshow/builder-templates/front-end/banner.php) file I started my attempt to find the content `<h1>` of the next slide so that it can be written in `<span id="next-title"></span>` which currently holds "Dummy text to style"

**Comment by jeremyfelt** [comment]
Fixed in #10
